name: Camera
authors: [NidoThe1st, BoatHub]
version: '${project.version}'
depend: [TimingSystem]
main: com.nido.camera.CameraPlugin
api-version: 1.19
commands:
  cam:
    description: "Base command for cameras"
    aliases: []